version: '3'
services:
  traefik:
    image: traefik:alpine
    container_name: traefik-container
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

  api:
    image: alanmunozlopez/api:api
    container_name: acid-api
    restart: always
    ports:
      - 5000:5000
    links:
      - redis
    depends_on:
      - redis
    networks:
      - traefik
  
  redis:
    image: redis:latest
    container_name: cache-db
    expose:
      - 6379
    restart: always

networks:
  traefik:
    external: true
