version: '3'
services:
  api:
    image: api
    container_name: acid-api
    restart: always
    ports:
      - 5000:5000
    links:
      - redis
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    container_name: cache-db
    expose:
      - 6379
    restart: always
