version: "3"

services:
  traefik:
    image: traefik:alpine
    container_name: 'traefik'
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

  api:
    image: alanmunozlopez/api:latest
    container_name: acid-api
    restart: always
    links:
      - redis
    depends_on:
      - redis
    labels:
      - "traefik.backend=restapi"
      - "traefik.frontend.rule=Host:api.alanmunoz.pro"
      - "traefik.enable=true"
      - "traefik.port=5000"
    networks:
      - traefik
  
  redis:
    image: redis:latest
    container_name: cache-db
    expose:
      - 6379
    restart: always
    labels:
      - "traefik.enable=false"
    networks:
      - traefik
  
  client:
    image: alanmunozlopez/web-app:latest
    container_name: forecast-app
    restart: always
    labels:
      - "traefik.backend=client"
      - "traefik.frontend.rule=Host:alanmunoz.pro"
      - "traefik.enable=true"
      - "traefik.port=3000"
    networks:
      - traefik

networks:
  traefik:
    external: true